language: python

sudo: false

env:
    - CONDA="python=2.7"
    - CONDA="python=3.5"
    - CONDA="python=3.6"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - conda config --add channels conda-forge --force
    - travis_retry conda create --yes -n TEST $CONDA --file requirements.txt
    - source activate TEST
    - travis_retry conda install --yes nose

script:
    - nosetests -w test
